### ISSUE TITLE
calledOnContract support for hardhat typechain contracts

### ISSUE THREAD

**Issue by Remscar** [TrueFiEng/Waffle#469]
I've been trying to use the `calledOnContract` chai matcher with a contract I deployed using a typechain generated factory (from the hardhat typechain plugin.)

When I try to use the matcher it gives me a type error informing me that the contract is not a valid contract.

example use:
```js
// setup
import { BasicController, BasicController__factory } from "../typechain";

controllerFactory = new BasicController__factory(creator);
controller = await controllerFactory.deploy();

// in a test
expect("foo").to.be.calledOnContract(controller); // error
```

I get the error `TypeError: argument must be a contract`

When using the open zeppelin upgradability plugin (deploys out a proxy) I get the same error.

It appears the internal check `contract instanceof ethers.Contract` does not recognize that they are both from the ethers library.

Perhaps there is a better way of checking if the input argument is an ethers contract since `instanceof` seems to be quite finnicky, especially when dealing with code across different libraries or versions

**Comment by Remscar** [comment]
Hi, is there any update on this or timeline on when this may be resolved? I really enjoy using this package, thank you for making it.

**Comment by wachulski** [comment]
Could you @Remscar provide more info about package versions you use? At least the following: waffle, typechain+typechain/ethers-v5(or -v4?) etc.

Bear in mind the current version of waffle (v3) targets ethers v5. I tried to repro your case with typechain/ethers-v4 generated types and the error messages were crystal clear on why the types do not match (structural inequalities).

**Comment by Remscar** [comment]
I am using 
@nomiclabs/hardhat-waffle ^2.0.1
ethereum-waffle ^3.3.0
typechain ^4.0.1
@typechain/ethers-v5 ^4.0.0



Here is a list of all my dependencies:
```
    "@eth-optimism/smock": "^1.0.1",
    "@nomiclabs/hardhat-ethers": "^2.0.1",
    "@nomiclabs/hardhat-etherscan": "^2.1.1",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts-upgradeable": "^3.4.1",
    "@openzeppelin/hardhat-upgrades": "^1.6.0",
    "@openzeppelin/upgrades-core": "^1.5.1",
    "@typechain/ethers-v5": "^4.0.0",
    "@typechain/hardhat": "^1.0.1",
    "@types/chai": "^4.2.14",
    "@types/mocha": "^8.2.0",
    "@types/node": "^14.14.25",
    "@typescript-eslint/eslint-plugin": "^4.16.1",
    "@typescript-eslint/parser": "^4.16.1",
    "chai": "^4.3.3",
    "dotenv": "^8.2.0",
    "eslint": "^7.21.0",
    "eslint-plugin-prettier": "^3.3.1",
    "ethereum-waffle": "^3.3.0",
    "ethers": "^5.0.31",
    "hardhat": "^2.0.10",
    "ipfs-http-client": "^49.0.4",
    "logdown": "^3.3.1",
    "prettier": "^2.2.1",
    "prettier-plugin-solidity": "^1.0.0-beta.4",
    "solhint": "^3.3.3",
    "solhint-plugin-prettier": "^0.0.5",
    "solidity-coverage": "^0.7.16",
    "ts-generator": "^0.1.1",
    "ts-node": "^9.1.1",
    "typechain": "^4.0.1",
    "typescript": "^4.1.4"
 ```

**Comment by germankuber** [comment]
Are there some update about this? Do you know other way to test the dependencies call?

**Comment by StErMi** [comment]
Hi there, just tested with 

```
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts": "^4.3.1",
    "chai": "^4.2.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.6",
    "hardhat": "^2.6.1",
    ````

and it's still not working. I get the same error 

```
     TypeError: argument must be a contract
      at Object.ensure (/Users/stermi/dev/web3/learn/challenge-1-decentralized-staking/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/utils.js:6:15)
      at Object.validateContract (/Users/stermi/dev/web3/learn/challenge-1-decentralized-staking/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/calledOnContractValidators.js:8:13)
      at Proxy.<anonymous> (/Users/stermi/dev/web3/learn/challenge-1-decentralized-staking/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/calledOnContract.js:8:38)
      at Proxy.methodWrapper (/Users/stermi/dev/web3/learn/challenge-1-decentralized-staking/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.<anonymous> (test/staker.js:134:32)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at runNextTicks (internal/process/task_queues.js:62:3)
      at listOnTimeout (internal/timers.js:523:9)
      at processTimers (internal/timers.js:497:7)
```

**Comment by StErMi** [comment]
Hi there, just tested with 

```
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts": "^4.3.1",
    "chai": "^4.2.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.6",
    "hardhat": "^2.6.1",
    ````

and it's still not working. I get the same error 

```
     TypeError: argument must be a contract
      at Object.ensure (/myproject/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/utils.js:6:15)
      at Object.validateContract (/myproject/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/calledOnContractValidators.js:8:13)
      at Proxy.<anonymous> (/myproject/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/calledOnContract/calledOnContract.js:8:38)
      at Proxy.methodWrapper (/myproject/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.<anonymous> (test/staker.js:134:32)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at runNextTicks (internal/process/task_queues.js:62:3)
      at listOnTimeout (internal/timers.js:523:9)
      at processTimers (internal/timers.js:497:7)
```

**Comment by rzadp** [comment]
Hey everyone, we have support for `calledOnContract` for hardhat in Waffle 4 now (in a setup with `@nomiclabs/hardhat-waffle` plugin).

Here is an example package in our repo, that tests all the hooks with hardhat, including the `calledOnContract`: https://github.com/TrueFiEng/Waffle/tree/master/waffle-hardhat
