### ISSUE TITLE
Issues with 4.0.0 and Ganache 7.0.3

### ISSUE THREAD

**Issue by alexdupre** [TrueFiEng/Waffle#667]
I've just upgraded to version 4.0.0 to have `london` support in `ganache`, but I noticed a few weird behaviors:

1. all tests that expected a `revert` now fail with
```
AssertionError: Expected transaction to be reverted, but other exception was thrown: Error: exceeds block gas limit
```

2. some successful tests print the following output: 
```
Error: invalid address (argument="address", value="0x01", code=INVALID_ARGUMENT, version=address/5.6.0)
    at Logger.makeError (/usr/home/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/usr/home/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.throwArgumentError (/usr/home/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:277:21)
    at Object.getAddress (/usr/home/contracts/node_modules/@ethersproject/address/src.ts/index.ts:109:16)
    at toRecordedCall (/usr/home/contracts/node_modules/@ethereum-waffle/provider/dist/cjs/CallHistory.js:93:46)
    at listener (/usr/home/contracts/node_modules/@ethereum-waffle/provider/dist/cjs/CallHistory.js:41:56)
    at map (/usr/home/contracts/node_modules/ganache/dist/node/webpack:/Ganache/core/node_modules/emittery/index.js:306:13)
    at Array.map (<anonymous>)
    at EthereumProvider.emit (/usr/home/contracts/node_modules/ganache/dist/node/webpack:/Ganache/core/node_modules/emittery/index.js:304:23) {
  reason: 'invalid address',
  code: 'INVALID_ARGUMENT',
  argument: 'address',
  value: '0x01'
}
```

**Comment by alexdupre** [comment]
For the records, I'm running the uniswap v2 test suite, and switching from waffle 4.0.0-alpha0 to 4.0.0 broke more than 50% of the tests.

These are some new considerations after additional digging:

1. on previous ganache-core version, the `eth_estimateGas` was returning an error if the transaction was reverting, on new ganache it returns a success response with 15M used gas (even if the smart contract has a single `revert()` line, all block gas is returned as consumed). Since my tests had a `gasLimit` of 10M they were failing. Removing the `gasLimit` option is a workaround for this issue, even if I don't think it's the right solution
2. all tests based on block timestamp broke: previous ganache-core version mined blocks always with the same timestamp, unless explicitely set via `evm_mine`, while the new version mine blocks with the current timestamp, making time-based testing almost impossible. I haven't found any workaround yet.
3. I noticed at least two other random issues for which I haven't found the cause yet: sometimes the event log emitted expectations fail, and sometimes the returned data from smart contracts doesn't seem to be updated and seems to come from a previous blockchain state.

**Comment by rzadp** [comment]
@alexdupre Please update to `4.0.0-alpha.7`, I have resolved one type of issue related to obtaining revert string.

I will continue digging into it.

**Comment by rzadp** [comment]
New alpha versions should fix (or offer workarounds in migration guide) these problems.
